; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
;default_envs = wt32sc01
default_envs = m5stack-core
;default_envs = m5stack-core2

[env]
platform = espressif32
framework = arduino
extra_scripts = pre:tools/gen_version_auto_h.py
build_flags = 
	-Wall -Werror
	-D DEBUG=1
	-D LV_CONF_INCLUDE_SIMPLE=1
	-D SOOGH_ENCODER_KEYS=1
	-D SOOGH_DOUBLEBUF=1
	; -D SOOGH_DEBUG=1
	-D KEYTOOL_FALLTHROUGH=1
	-I .
	-I include
lib_deps =
	https://github.com/lvgl/lvgl.git#release/v9.2
    https://github.com/lovyan03/LovyanGFX#1.2.19
	https://github.com/knifter/lib-tools
	https://github.com/knifter/lib-soogh
	https://github.com/knifter/lib-TwoWireDevice
	https://github.com/knifter/lib-FPID
	https://github.com/knifter/lib-M5KMeter
	https://github.com/knifter/lib-MAX31865
	https://github.com/knifter/lib-MCP9600
	https://github.com/knifter/lib-BM8563
	https://github.com/knifter/lib-GP8413
	https://github.com/knifter/lib-MLX90614
	https://github.com/knifter/lib-SHT3x
	https://github.com/knifter/lib-SPIDevice
	https://github.com/knifter/lib-SprintIR
	https://github.com/knifter/lib-UnitSSR

monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 1000000
	
[env:m5stack-core]
board = m5stack-core-esp32
build_flags =
	${env.build_flags}
	-D SOOGH_DEV_M5CORE
lib_deps = 
	${env.lib_deps}
	; m5stack/M5Stack

[env:m5stack-core2]
board = m5stack-core2
build_flags =
	${env.build_flags}
	-D SOOGH_DEV_M5CORE2
lib_deps = 
	${env.lib_deps}
	; m5stack/M5Core2@^0.0.6

[env:wt32sc01]
board = esp32-s3-devkitc-1
upload_speed = 921600
build_flags =
	${env.build_flags}
	-DARDUINO_USB_MODE=1
   	-DARDUINO_USB_CDC_ON_BOOT=0
	; -DLV_CONF_INCLUDE_SIMPLE
	; -DLV_COMP_CONF_INCLUDE_SIMPLE
	; -DLV_LVGL_H_INCLUDE_SIMPLE
	-DBOARD_HAS_PSRAM
	;-DDEBUG_TOUCH
	-mfix-esp32-psram-cache-issue
	-D SOOGH_DEV_WT32SC01
lib_deps = 
	${env.lib_deps}
	; m5stack/M5Core2@^0.0.6
